" The Power of Habit
nnoremap d$ <NOP>
nnoremap y$ <NOP>
nnoremap c$ <NOP>

" Preliminary
set nocompatible " only vim!
syntax enable " enable syntax processing
filetype on
filetype indent on
filetype plugin on

" Tabs and Spaces
set tabstop=2 " # of visual spaces per TAB
set softtabstop=2 " # of spaces in TAB when editing
set shiftwidth=2
set expandtab " TABs are spaces

" User Interface
set number " show line numbers
set showcmd " show command in bottom bar
set cursorline " highlight current line

" NETRW Settings (https://shapeshed.com/vim-netrw/)
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END

" Install VimPlug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'mattn/emmet-vim'
Plug 'https://github.com/vim-ruby/vim-ruby'
Plug 'pangloss/vim-javascript'
call plug#end()
